name: Nix Build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build (${{ matrix.package }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        package: [blender-with-cuda, blender-with-cuda-unstable]
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05
          extra_nix_config: |
            max-jobs = 2
            cores = 3
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-gha-cache: true
          use-flakehub: false
      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: adithyagenie
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false
          pathsToPush: result
          cachixArgs: -j1
      - name: Build
        run: |
          set -euo pipefail
          nix build ".#${{ matrix.package }}" \
            --print-out-paths \
            --out-link result
