name: Nix Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        system: [x86_64-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: adithyagenie
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --json | jq -r '.[].outputs | to_entries[].value' | cachix push adithyagenie
